# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

blank_issues_enabled: false
contact_links:
  - name: Discussions Forum
    url: https://github.com/dotanuki-labs/rust-cli-tool-scaffold/discussions
    about: Use this space to ask and answer questions and follow community annoucements.
  - name: Security Reports
    url: https://github.com/dotanuki-labs/rust-cli-tool-scaffold/security/advisories
    about: Please report potential security vulnerabilities here.
