# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

name: cd

on: workflow_dispatch

permissions:
  id-token: write
  contents: read
  pages: write
  attestations: write
  packages: write

jobs:
  docs:
    uses: ./.github/workflows/cd-docs.yml

  docker:
    uses: ./.github/workflows/cd-docker.yml

  rust:
    uses: ./.github/workflows/cd-rust.yml
    secrets:
      DOTANUKI_BOT_TOKEN: ${{ secrets.DOTANUKI_BOT_TOKEN }}
      CRATESIO_PUBLISH_TOKEN: ${{ secrets.CRATESIO_PUBLISH_TOKEN }}

  all-deploys:
    runs-on: warp-ubuntu-2204-arm64-2x
    needs: [docs, docker, rust]
    steps:
      - name: Report success
        run: |
          echo "All artifacts deploys âœ…"
          echo "Go to Github releases to publish the draft version"
          echo "https://github.com/dotanuki-labs/releases"
