# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

name: cd

on: workflow_dispatch

permissions:
  contents: read

jobs:
  docs:
    uses: ./.github/workflows/cd-docs.yml
    permissions:
      contents: read
      pages: write
      id-token: write

  docker:
    uses: ./.github/workflows/cd-docker.yml
    permissions:
      contents: read
      id-token: write
      packages: write

  rust:
    uses: ./.github/workflows/cd-rust.yml
    permissions:
      contents: read
      id-token: write
      attestations: write
    secrets:
      DOTANUKI_BOT_TOKEN: ${{ secrets.DOTANUKI_BOT_TOKEN }}
      CRATESIO_PUBLISH_TOKEN: ${{ secrets.CRATESIO_PUBLISH_TOKEN }}

  all-deploys:
    timeout-minutes: 5
    runs-on: ubuntu-24.04
    needs: [docs, docker, rust]
    steps:
      - name: Report success
        run: |
          echo "All artifacts deploys âœ…"
          echo "Go to Github releases to publish the draft version"
          echo "https://github.com/dotanuki-labs/releases"
