# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

name: cd-docs

on:
  workflow_call:

jobs:
  deploy-pages:
    runs-on: warp-ubuntu-2404-x64-2x # ubuntu-24.04
    timeout-minutes: 10
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout source
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          persist-credentials: false

      - name: Prepare documentation assets
        uses: dotanuki-labs/github-actions/foss/prepare-ghpages@cee89698bd9caac6c9e3f1728b7339ddccd28639

      - name: Deploy assets to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
