# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

name: cd-docker

on:
  workflow_call:

jobs:
  docker-images:
    runs-on: ${{ matrix.build-args.runner }}
    timeout-minutes: 10
    strategy:
      matrix:
        build-args:
          - platform: amd64
            runner: warp-ubuntu-2404-x64-4x
          - platform: arm64
            runner: warp-ubuntu-2404-arm64-4x

    steps:
      - name: Project checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: Compute current version
        id: release-tag
        uses: ./.github/actions/compute-version

      - name: Compute docker metadata
        id: docker-metadata
        uses: docker/metadata-action@318604b99e75e41977312d83839a89be02ca4893 # v5
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Set up docker-buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Log in to Github Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          push: true
          provenance: false
          platforms: linux/${{ matrix.build-args.platform }}
          labels: ${{ steps.docker-metadata.outputs.labels }}
          annotations: ${{ steps.docker-metadata.outputs.annotations }}
          outputs: type=registry,push=true
          tags: ghcr.io/${{ github.repository }}:${{ steps.release-tag.outputs.computed }}-${{ matrix.build-args.platform }}

  merge-manifest:
    runs-on: warp-ubuntu-2404-x64-4x
    timeout-minutes: 5
    needs: docker-images

    steps:
      - name: Project checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: Compute current version
        id: release-tag
        uses: ./.github/actions/compute-version

      - name: Log in to Github Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Docker manifest
        run: |
          docker manifest create "$latest" --amend "$package"-amd64 --amend "$package"-arm64
          docker manifest annotate --arch amd64 --os linux "$latest" "$package"-amd64
          docker manifest annotate --arch arm64 --os linux "$latest" "$package"-arm64
          docker manifest inspect "$latest"
          docker manifest push "$latest"
        env:
          package: ghcr.io/${{ github.repository }}:${{ steps.release-tag.outputs.computed }}
          latest: ghcr.io/${{ github.repository }}:latest
