# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

name: cd-docs

on:
  workflow_call:

jobs:
  deploy-pages:
    runs-on: warp-ubuntu-2404-x64-2x # ubuntu-24.04
    timeout-minutes: 10
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout source
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: Prepare documentation assets
        uses: dotanuki-labs/github-actions/foss/prepare-ghpages@771d6c7a54dca1c45d374cade8f9f5ff13f82782

      - name: Deploy assets to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
