# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

name: cd-rust

permissions:
  contents: read

on:
  workflow_call:
    secrets:
      CRATESIO_PUBLISH_TOKEN:
        required: true
      DOTANUKI_BOT_TOKEN:
        required: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-24.04, macos-15 ]

    steps:
      - name: Project Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Setup Rust tools
        uses: ./.github/actions/setup-rust
        with:
          install-extra-tools: true

      - name: Generates build artifacts
        run: cargo xtasks artifacts binaries

      - name: Archive binaries
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: sculptor-binaries-${{ runner.os }}
          path: artifacts

  extras:
    needs: build
    runs-on: ubuntu-24.04

    steps:
      - name: Project Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Fetch executable from previous build
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          path: artifacts
          pattern: sculptor-binaries-*

      - name: Setup Rust tools
        uses: ./.github/actions/setup-rust

      - name: Generate additional artifacts
        run: cargo xtasks artifacts extras

      - name: Archive checksums
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: checksums.txt
          path: artifacts/checksums.txt

      - name: Archive SBOM
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: sbom-${{ github.sha }}.json
          path: crates/sculptor/sculptor.cdx.json

  github:
    needs: extras
    runs-on: ubuntu-24.04

    steps:
      - name: Project Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Fetch binaries from previous build
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          path: artifacts
          pattern: sculptor-binaries-*

      - name: Build provenance for binaries
        uses: actions/attest-build-provenance@00014ed6ed5efc5b1ab7f7f34a39eb55d41aa4f8 # v3.1.0
        if: false
        with:
          subject-path: artifacts/**/*

      - name: Fetch checksums from previous build
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          path: artifacts
          pattern: checksums.txt

      - name: Compute current version
        id: release-tag
        uses: ./.github/actions/compute-version

      - name: Publish draft release on Github
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          name: ${{ steps.release-tag.outputs.version }}
          tag_name: ${{ steps.release-tag.outputs.version }}
          token: ${{ secrets.DOTANUKI_BOT_TOKEN }}
          generate_release_notes: true
          draft: true
          files: |
            artifacts/**/*

  cratesio:
    needs: github
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
      - name: Project Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Setup Rust tools
        uses: ./.github/actions/setup-rust

      - name: Publish on crates.io
        run: cargo publish -p sculptor --token ${{ secrets.CRATESIO_PUBLISH_TOKEN }} --dry-run # zizmor: ignore[use-trusted-publishing]
