# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

name: ci

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  compliance:
    uses: ./.github/workflows/ci-compliance.yml
    permissions:
      contents: read

  docs:
    needs: compliance
    uses: ./.github/workflows/ci-docs.yml
    permissions:
      contents: read
      pages: read
      id-token: write

  docker:
    needs: compliance
    uses: ./.github/workflows/ci-docker.yml
    permissions:
      contents: read

  rust:
    needs: compliance
    uses: ./.github/workflows/ci-rust.yml
    permissions:
      contents: read

  scorecard:
    needs: compliance
    uses: ./.github/workflows/ci-scorecards.yml
    permissions:
      contents: read
      security-events: write
      id-token: write

  all-checks:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    needs: [compliance, docs, rust, docker, scorecard]
    steps:
      - name: Report success
        run: echo "Great job âœ…"
