# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

name: ci-compliance

on:
  workflow_call:

jobs:
  checks:
    timeout-minutes: 3
    runs-on: warp-ubuntu-2404-x64-2x # ubuntu-24.04
    steps:
      - name: Project checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 20
          persist-credentials: false

      - name: Check typos on source files
        uses: crate-ci/typos@0c17dabcee8b8f1957fa917d17393a23e02e1583 # v1.36.3

      - name: Check commit conventions
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: crate-ci/committed@15229711f8f597474c0b636f327cde5969f9a529 # v1.1.7

      - name: Check MIT license on source files
        uses: dotanuki-labs/github-actions/foss/check-licenses@3ec738285d4743905ec3e2b44e58f2e0901cb945
        with:
          file-patterns: "*.rs,*.yml"
          license: "mit"

      - name: Check issues with GHA Workflows
        uses: zizmorcore/zizmor-action@e673c3917a1aef3c65c972347ed84ccd013ecda4 # v0.2.0
        with:
          advanced-security: false

