# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

name: ci-compliance

permissions:
  contents: read

on:
  workflow_call:

jobs:
  checks:
    timeout-minutes: 5
    runs-on: ubuntu-24.04
    steps:
      - name: Project checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          fetch-depth: 20
          persist-credentials: false

      - name: Check typos on source files
        uses: crate-ci/typos@2d0ce569feab1f8752f1dde43cc2f2aa53236e06 # v1.40.0

      - name: Check commit conventions
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: crate-ci/committed@bb02f309663f9baced8dbd5fdd80c6369ddf3efd # v1.1.8

      - name: Check MIT license on source files
        run: docker run --rm -v $(pwd):/github/workspace ghcr.io/korandoru/hawkeye:v6.3.0 check

      - name: Check issues with GHA Workflows
        uses: zizmorcore/zizmor-action@e639db99335bc9038abc0e066dfcd72e23d26fb4 # v0.3.0
        with:
          advanced-security: false
