# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

name: Compliance

on:
  workflow_call:

jobs:
  checks:
    runs-on: warp-ubuntu-2404-x64-2x # ubuntu-24.04
    steps:
      - name: Project Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 10

      - name: Check typos on source files
        uses: crate-ci/typos@85f62a8a84f939ae994ab3763f01a0296d61a7ee # v1.36.2

      - name: Check commit conventions
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: crate-ci/committed@15229711f8f597474c0b636f327cde5969f9a529 # v1.1.7

      - name: Check MIT license on source files
        uses: dotanuki-labs/github-actions/foss/check-licenses@main
        with:
          file-patterns: "*.rs,*.yml"
          license: "mit"
