# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

name: Docker

on:
  workflow_call:

jobs:
  build-push:
    runs-on: warp-ubuntu-2404-x64-4x
    services:
      local-registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Project Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Docker metadata
        id: docker-metadata
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5
        with:
          images: localhost:5000/${{ github.repository }}

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
        with:
          driver-opts: |
            network=host

      - name: Build and push container image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          push: true
          provenance: false
          platforms: linux/amd64
          labels: ${{ steps.docker-metadata.outputs.labels }}
          annotations: ${{ steps.docker-metadata.outputs.annotations }}
          outputs: type=registry,push=true
          tags: localhost:5000/${{ github.repository }}:${{ github.sha }}-amd64
          cache-from: type=gha,url=http://127.0.0.1:49160/,version=1
          cache-to: type=gha,url=http://127.0.0.1:49160/,mode=max,version=1
