# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

name: ci-docker

on:
  workflow_call:

jobs:
  build-push:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    services:
      local-registry:
        image: registry:3@sha256:cd92709b4191c5779cd7215ccd695db6c54652e7a62843197e367427efb84d0e
        ports:
          - 5000:5000
    steps:
      - name: Project checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: Compute current version
        id: release-tag
        uses: ./.github/actions/compute-version

      - name: Docker metadata
        id: docker-metadata
        uses: docker/metadata-action@318604b99e75e41977312d83839a89be02ca4893 # v5
        with:
          images: localhost:5000/${{ github.repository }}

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
        with:
          driver-opts: |
            network=host

      - name: Build and push container image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          push: true
          provenance: false
          platforms: linux/amd64
          labels: ${{ steps.docker-metadata.outputs.labels }}
          annotations: ${{ steps.docker-metadata.outputs.annotations }}
          outputs: type=registry,push=true
          tags: localhost:5000/${{ github.repository }}:${{ steps.release-tag.outputs.computed }}-amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
