# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

name: ci-docker

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build-push:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    services:
      local-registry:
        image: registry:3@sha256:650406796a6a7c0c45d098cdcc4d6c5f5ae47c62e9fec489d287e2bfde38fe63
        ports:
          - 5000:5000
    steps:
      - name: Project checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Compute current version
        id: release-tag
        uses: ./.github/actions/compute-version

      - name: Docker metadata
        id: docker-metadata
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
        with:
          images: localhost:5000/${{ github.repository }}

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
        with:
          driver-opts: |
            network=host

      - name: Build and push container image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          push: true
          provenance: false
          platforms: linux/amd64
          labels: ${{ steps.docker-metadata.outputs.labels }}
          annotations: ${{ steps.docker-metadata.outputs.annotations }}
          outputs: type=registry,push=true
          tags: localhost:5000/${{ github.repository }}:${{ steps.release-tag.outputs.computed }}-amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
