# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

name: ci-docs

on:
  workflow_call:

jobs:
  lint-build:
    runs-on: warp-ubuntu-2404-x64-2x # ubuntu-24.04
    timeout-minutes: 5
    steps:
      - name: Project checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          persist-credentials: false

      - name: Setup Rust tools
        uses: ./.github/actions/setup-rust

      - name: Lint Markdown files
        run: cargo install rumdl && rumdl check

      - name: Build and archive documentation assets
        uses: dotanuki-labs/github-actions/foss/prepare-ghpages@8bd526177673e42dbad9b0a7080c91746a089fd5
