# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

name: ci-docs

on:
  workflow_call:

permissions:
  contents: read

jobs:
  lint-build:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - name: Project checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: Setup Rust tools
        uses: ./.github/actions/setup-rust

      - name: Lint Markdown files
        run: cargo install rumdl && rumdl check

      - name: Build and archive documentation assets
        uses: dotanuki-labs/github-actions/foss/prepare-ghpages@771d6c7a54dca1c45d374cade8f9f5ff13f82782
