# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

name: ci-docs

on:
  workflow_call:

permissions:
  contents: read

jobs:
  lint-build:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - name: Project checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Lint Markdown files
        uses: rvben/rumdl@0ef10a921de0114838278edcf1a2cf0d5d24cc48 # v0.0.195

      - name: Build and archive documentation assets
        uses: dotanuki-labs/github-actions/foss/prepare-ghpages@94e620b50bc8470655184441061d4bfa400dfb5f
