# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

name: ci-security

permissions:
  contents: read

on:
  workflow_call:

jobs:
  checks:
    permissions:
      security-events: write
      id-token: write

    timeout-minutes: 5
    runs-on: ubuntu-24.04
    steps:
      - name: Project checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: Check issues with GHA Workflows
        uses: zizmorcore/zizmor-action@e639db99335bc9038abc0e066dfcd72e23d26fb4 # v0.3.0
        with:
          advanced-security: false

      - name: Run OSSF security scorecard analysis
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a # v2.4.3
        with:
          results_file: scorecard-results.sarif
          results_format: sarif
          publish_results: true

      - name: Save scorecard analysis results
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: SARIF file
          path: scorecard-results.sarif

      - name: Upload to code-scanning
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: github/codeql-action/upload-sarif@e12f0178983d466f2f6028f5cc7a6d786fd97f4b # v4.31.4
        with:
          sarif_file: scorecard-results.sarif
