# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

name: ci-sculptor

on:
  workflow_call:

jobs:
  rust-cli:
    runs-on: warp-macos-15-arm64-6x

    steps:
      - name: Project checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          persist-credentials: false

      - name: Sculpt a CLI from Rust build
        run: |
          ./sculpt.sh test-cli
          cargo build
          ./target/debug/test-cli --help

  docker-cli:
    runs-on: warp-ubuntu-2404-x64-4x

    steps:
      - name: Project checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          persist-credentials: false

      - name: Sculpt and run a Docker build
        run: |
          ./sculpt.sh test-cli
          docker build -t dotanuki-labs/test-cli .
          docker run --rm -v "${PWD}/tmp" dotanuki-labs/test-cli --help
