# Copyright 2024 Dotanuki Labs
# SPDX-License-Identifier: MIT

name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-22.04
    steps:
      - name: Project Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Check typos on source files
        uses: dotanuki-labs/github-actions/quality/typos@main

      - name: Lint Markdown files
        uses: dotanuki-labs/github-actions/quality/markdown@main

      - name: Check MIT license on source files
        uses: dotanuki-labs/github-actions/foss/check-licenses@main
        with:
          file-patterns: "*.sh,*.rs,*.yml"
          license: "mit"

  lint:
    runs-on: ubuntu-22.04
    needs: docs

    steps:
      - name: Project Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Lint Bash scripts
        uses: dotanuki-labs/github-actions/quality/bash@main

      - name: Lint project
        run: ./krabby.sh lint

  tests:
    runs-on: ubuntu-22.04
    needs: docs

    steps:
      - name: Project Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Lint Bash scripts
        uses: dotanuki-labs/github-actions/quality/bash@main

      - name: Setup CI
        uses: ./.github/actions/setup-rust

      - name: Run tests
        run: ./krabby.sh tests


  build:
    needs: docs
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-22.04', 'macos-14' ]

    steps:
      - name: Project Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup CI
        uses: ./.github/actions/setup-rust

      - name: Cross-compilation against some targets
        run: ./krabby.sh assemble

      - name: Archive binaries
        uses: actions/upload-artifact@89ef406dd8d7e03cfd12d9e0a4a378f454709029 # v4.3.5
        with:
          name: rust-cli-tool-scaffold-binaries-${{ runner.os }}
          path: artifacts

  security:
    runs-on: ubuntu-22.04
    needs: [lint, tests, build]

    steps:
      - name: Project Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Check supply-chain issues
        run: ./krabby.sh security

      - name: Archive SBOM
        uses: actions/upload-artifact@89ef406dd8d7e03cfd12d9e0a4a378f454709029 # v4.3.5
        with:
          name: sbom-${{ github.sha }}.json
          path: rust-cli-tool-scaffold.cdx.json
