# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  compliance:
    uses: ./.github/workflows/compliance.yml

  docs:
    needs: compliance
    uses: ./.github/workflows/docs.yml

  rust:
    needs: compliance
    uses: ./.github/workflows/rust.yml

  docker:
    needs: compliance
    uses: ./.github/workflows/docker.yml

  sculptor:
    needs: compliance
    uses: ./.github/workflows/sculptor.yml

  all-checks:
    runs-on: warp-ubuntu-2204-arm64-2x
    needs: [compliance, docs, rust, docker, sculptor]
    steps:
      - name: Report success
        run: echo "Great job âœ…"
