name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Project Checkout
        uses: actions/checkout@v4.1.1

      - name: Check active Rust toolchain
        run: rustup show active-toolchain && rustup update

      - name: Check code formatting
        run: cargo fmt --check

      - name: Check code smells
        run: cargo clippy --all-targets --all-features

      - name: Build project
        run: cargo build
