name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Project Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Install just
        run: sudo snap install --edge --classic just

      - name: Install Rust toolchain
        run: just toolchain

      - name: Check code smells
        run: just lint

      - name: Run tests
        run: just test

      - name: Verify supply chain security
        run: just security

      - name: Archive SBOM
        uses: actions/upload-artifact@v4.3.1
        with:
            name: sbom-${{ github.sha }}.json
            path: rust-cli-tool-scaffold.cdx.json

      - name: Submit SBOM to Github Code Security
        uses: evryfs/sbom-dependency-submission-action@v0.0.14
        with:
            sbom-files: rust-cli-tool-scaffold.cdx.json
