# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

name: Docs

on:
  workflow_call:
    inputs:
      must-deploy:
        required: true
        type: boolean

jobs:
  lint:
    runs-on: warp-ubuntu-2404-x64-2x # ubuntu-24.04
    steps:
      - name: Project Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Lint Markdown files
        uses: dotanuki-labs/github-actions/quality/markdown@main

  build-only:
    needs: lint
    if: ${{ ! inputs.must-deploy }}
    runs-on: warp-ubuntu-2404-x64-2x # ubuntu-24.04

    steps:
      - name: Project Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Build and archive documentation assets
        uses: dotanuki-labs/github-actions/foss/prepare-ghpages@main

  deploy:
    needs: lint
    if: ${{ inputs.must-deploy }}
    runs-on: warp-ubuntu-2404-x64-2x # ubuntu-24.04

    steps:
      - name: Project Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Build and archive documentation assets
        uses: dotanuki-labs/github-actions/foss/prepare-ghpages@main

      - name: Deploy assets to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
