# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

name: dogfood

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  dogfood-rust:
    runs-on: macos-15

    steps:
      - name: Project checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: Sculpt a CLI from Rust build
        run: |
          ./sculpt.sh test-cli
          cargo build
          ./target/debug/test-cli --help

  dogfood-docker:
    runs-on: ubuntu-24.04

    steps:
      - name: Project checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: Sculpt and run a Docker build
        run: |
          ./sculpt.sh test-cli
          docker build -t dotanuki-labs/test-cli .
          docker run --rm -v "${PWD}/tmp" dotanuki-labs/test-cli --help
