# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

name: Scaffolding

on:
  pull_request:

jobs:
  scaffolding-test-rust-build:
    runs-on: macos-15

    steps:
      - name: Project Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Scaffold a CLI from Rust build
        run: |
          ./scaffold.sh testcli
          cargo build
          ./target/debug/testcli --help

  scaffolding-test-docker-build:
    runs-on: ubuntu-24.04

    steps:
      - name: Project Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Scaffold a CLI from Docker build
        run: |
          ./scaffold.sh testcli
          docker build -t dotanuki-labs/testcli .
          docker run --rm -v "${PWD}/tmp" dotanuki-labs/testcli --help
